#!/bin/bash
i3-msg "workspace 1: web; append_layout $XDG_CONFIG_HOME/i3/ws1.json"
i3-msg "workspace 2: terminal; append_layout $XDG_CONFIG_HOME/i3/ws2.json"
i3-msg "workspace 3: code; append_layout $XDG_CONFIG_HOME/i3/ws3.json"
i3-msg "workspace 4: music; append_layout $XDG_CONFIG_HOME/i3/ws4.json"
i3-msg "workspace 1: web"

qutebrowser & disown
xfce4-terminal --title terminal & disown
xfce4-terminal --title terminal & disown
xfce4-terminal --title terminal & disown
code --extensions-dir "$XDG_DATA_HOME/vscode/extensions" & disown
glava & disown
xfce4-terminal --title ncmpcpp -x ncmpcpp & disown
xfce4-terminal --title tty-clock -x tty-clock -ct -f '%a %b %d' & disown
xfce4-terminal --title htop -x htop --delay 50 & disown
