#!/bin/bash
resolution="$(xdpyinfo | awk '/dimensions/ { print $2 }')"
W="${resolution%x*}"
H="${resolution#*x}"
w="$(bc <<< "$W * 0.4 / 1")"
h="$(bc <<< "$H * 0.4 / 1")"

i3Config="$XDG_CONFIG_HOME/i3/config"
gap="$(awk '/^gaps inner/ { print $3 }' "$i3Config")"
border="$(awk '/^default_border pixel/ { print $3 }' "$i3Config")"
margin="$((gap + border))"

x="$(bc <<< "$W - $w - 2 * $margin")"
y="$(bc <<< "$H - $h - 2 * $margin")"

i3-msg -q 'fullscreen disable; floating enable; sticky enable'
i3-msg -q "resize set $w px $h px, move position $x px $y px"
