#!/bin/bash
launch() {
    xfce4-terminal --title quake-terminal &
    xdotool search --sync --name quake-terminal
    i3-msg "[title=\"quake-terminal\"] move scratchpad"
}

format() {
    resolution="$(xdpyinfo | awk '/dimensions/ { print $2 }')"
    w="${resolution%x*}"

    if xdotool search --class polybar; then
        xdotool search --class polybar getwindowgeometry
        polybarDimensions="$(xdotool search --class polybar getwindowgeometry \
            | awk '/Geometry/ { print $2 }')"
        polybarHeight="${polybarDimensions#*x}"
    fi

    i3Config="$XDG_CONFIG_HOME/i3/config"
    gap="$(awk '/^gaps inner/ { print $3 }' "$i3Config")"

    i3-msg "[title=\"quake-terminal\"]
    move position $gap px ${polybarHeight:-$gap} px,
    resize set $((w - 2 * gap)) px 50 ppt"
}

toggle() {
    i3-msg "[title=\"quake-terminal\"] scratchpad show"
}

case "$1" in
    --launch)
        launch
        format
        ;;
    --format)
        format
        ;;
    --toggle)
        toggle
        format
        ;;
esac
