#!/bin/bash
accounts="$(lpass ls --format '%an' main | tail -n +1 | uniq)"
account="$(rofi -dmenu -i -p account <<< "$accounts")"
if [[ "$account" == "Debit Card" ]]; then
    lpass show --field Number --clip "$account"
else
    lpass show --password --clip "$account"
fi
if [[ -v QUTE_FIFO ]]; then
    echo "insert-text $(lpass show --password "$account")" >> "$QUTE_FIFO"
fi
