. "$HOME/.config/xdg-compliance"

[[ -r "$XDG_CONFIG_HOME/bash/bashrc" ]] && . "$XDG_CONFIG_HOME/bash/bashrc"

XINITRC="$XDG_CONFIG_HOME/xorg/xinitrc"
LOG="$XDG_DATA_HOME/xorg/xsession-errors"

if [ "$(tty)" = "/dev/tty1" ]; then
    startx "$XINITRC" -- -keeptty 2>>"$LOG"
fi
